"""add view counter to video model

Revision ID: 5736936de21d
Revises: adf13ceb879b
Create Date: 2026-02-20 17:27:51.948459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5736936de21d'
down_revision: Union[str, Sequence[str], None] = 'adf13ceb879b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'videos',
        sa.Column(
            'views',
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False
        )
    )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'views')
    # ### end Alembic commands ###
